name: Rebuild site
run-name: ${{ github.actor }} is deploying...
# if file not solved errors happen, run this after renaming those files: git rm -r --cached . && git add --all .
on: 
  push:
    branches: [ source ]
jobs:
  Rebuild-site:
      runs-on: ubuntu-latest
      steps:
        - run: |
                git config --global user.email "surajkukati95@gmail.com"
                git config --global user.name "surajk95"
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Install dependencies
          run: npm ci --legacy-peer-deps
        - name: Deploy
          run: npm run deploy
  
